In [1]:
#get_dummies
import pandas as pd



In [3]:
df = pd.DataFrame([  
            ['green' , 'm'],   
            ['red'   , 'n'],   
            ['blue'  , 'q']])  

df.columns = ['color',  'class'] 
pd.get_dummies(df) 

color_blue  color_green  color_red  class_m  class_n  class_q
0           0            1          0        1        0        0
1           0            0          1        0        1        0
2           1            0          0        0        0        1

In [4]:
# 一个数组为例 imputer
import numpy as np
from sklearn.preprocessing import Imputer
train_X = np.array([[1, 2], [np.nan, 3], [7, 6]])
imp = Imputer(missing_values=np.nan , strategy='mean', axis=0)
imp.fit(train_X)

Imputer(axis=0, copy=True, missing_values=nan, strategy='mean', verbose=0)

In [5]:
imp.statistics_

array([4.        , 3.66666667])

In [6]:
test_X = np.array([[np.nan, 2], [6, np.nan], [7, 6]])
imp.transform(test_X)


array([[4.        , 2.        ],
       [6.        , 3.66666667],
       [7.        , 6.        ]])

In [7]:
imp.fit_transform(test_X)

array([[6.5, 2. ],
       [6. , 4. ],
       [7. , 6. ]])

In [8]:
imp.statistics_

array([6.5, 4. ])

In [9]:
# 稀疏矩阵
import scipy.sparse as sp
from sklearn.preprocessing import Imputer
X = sp.csc_matrix([[1, 2], [0, 3], [7, 6]])
imp = Imputer(missing_values = 0 , strategy = 'mean',axis=0)
imp.fit(X)
test_X = sp.csc_matrix([[0, 2], [6, 0], [7, 6]])
imp.transform(test_X)


array([[4.        , 2.        ],
       [6.        , 3.66666667],
       [7.        , 6.        ]])

In [10]:
 imp.statistics_

array([4.        , 3.66666667])